# Generated by Django 3.2.2 on 2021-05-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home_text',
            new_name='Hometext',
        ),
    ]
