# Generated by Django 3.2.2 on 2021-05-11 11:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_text_text_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_home',
            name='fill_text',
            field=ckeditor.fields.RichTextField(verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='text_home',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=50, verbose_name='Название'),
        ),
    ]
