# Generated by Django 3.2.2 on 2021-05-10 16:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_artiles_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiles',
            name='video',
        ),
        migrations.AlterField(
            model_name='artiles',
            name='fill_text',
            field=ckeditor.fields.RichTextField(verbose_name='Статья'),
        ),
    ]
