# Generated by Django 3.2.2 on 2021-05-10 17:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210510_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='title',
            field=ckeditor.fields.RichTextField(default='Мая первая статья', max_length=50, verbose_name='Название'),
        ),
    ]
