# Generated by Django 3.2.2 on 2021-05-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210510_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiles',
            name='essence',
            field=models.CharField(blank=True, max_length=50, verbose_name='Суть'),
        ),
    ]
